/** نصوص تطبيق بوابة العميل. الأسلوب: بسيط ومباشر (راجع docs/design/voice-and-tone.md). */
export const portalCopy = {
  "p.brand": "Hyper-Tech",
  "p.tagline": "بوابة عملاء الجملة",

  /* ---- الدخول ---- */
  "p.login.title": "ادخل لحسابك",
  "p.login.sub": "بالموبايل أو الإيميل اللي سجّلت بيه.",
  "p.login.identifier": "الموبايل أو الإيميل",
  "p.login.password": "كلمة السر",
  "p.login.remember": "افتكرني على الجهاز ده",
  "p.login.submit": "ادخل",
  "p.login.forgot": "نسيت كلمة السر؟",
  "p.login.join": "انضم لشركتك بالكود",
  "p.login.apply": "قدّم كعميل جديد",
  "p.login.track": "تابع طلب الانضمام",
  "p.login.required": "اكتب الموبايل أو الإيميل وكلمة السر.",
  "p.choose.title": "هتدخل على أنهي شركة؟",
  "p.choose.sub": "حسابك مربوط بأكتر من شركة.",
  "p.choose.owner": "رئيس الشركة",
  "p.choose.back": "رجوع للدخول",
  "p.choose.expired": "الجلسة خلصت. ادخل من الأول.",

  /* ---- الانضمام بالكود ---- */
  "p.join.title": "انضم لشركتك",
  "p.join.sub": "اطلب كود الشركة من رئيس شركتك.",
  "p.join.code": "كود الشركة",
  "p.join.name": "اسمك",
  "p.join.phone": "رقم موبايلك",
  "p.join.email": "الإيميل",
  "p.join.password": "كلمة السر",
  "p.join.passwordHint": "6 حروف على الأقل. لو عندك حساب قبل كده اكتب كلمة سرك الحالية.",
  "p.join.submit": "انضم",
  "p.join.codeFirst": "اكتب كود الشركة كامل الأول.",
  "p.join.done.joined": "اتضفت لـ {company}",
  "p.join.done.joinedBody": "تقدر تدخل دلوقتي بالموبايل وكلمة السر.",
  "p.join.done.pending": "طلبك وصل",
  "p.join.done.pendingBody": "رئيس {company} هيراجع طلبك، وهتقدر تدخل أول ما يوافق.",
  "p.join.goLogin": "ادخل",

  /* ---- تقديم عميل جديد ---- */
  "p.apply.title": "قدّم كعميل جديد",
  "p.apply.sub": "هنراجع طلبك ونرجعلك. بياخد غالبًا يوم شغل.",
  "p.apply.step.company": "الشركة",
  "p.apply.step.contact": "التواصل",
  "p.apply.step.review": "راجع وابعت",
  "p.apply.companyName": "اسم الشركة",
  "p.apply.city": "المحافظة",
  "p.apply.address": "العنوان",
  "p.apply.volume": "الحجم الشهري المتوقع",
  "p.apply.volumeHint": "مثلًا: 500 قطعة",
  "p.apply.fullName": "اسمك",
  "p.apply.phone": "موبايلك",
  "p.apply.email": "الإيميل",
  "p.apply.notes": "ملاحظات",
  "p.apply.send": "ابعت الطلب",
  "p.apply.draft": "اللي كتبته بيتحفظ على الجهاز لحد ما تبعت.",
  "p.apply.fixFirst": "اكمل بيانات الشركة والتواصل الأول.",
  "p.apply.done.title": "طلبك اتبعت",
  "p.apply.done.ref": "رقم المتابعة",
  "p.apply.done.body": "احتفظ بالرقم ده. تقدر تتابع بيه حالة طلبك.",
  "p.apply.done.track": "تابع الطلب",

  /* ---- تتبّع ---- */
  "p.track.title": "تابع طلب الانضمام",
  "p.track.ref": "رقم المتابعة",
  "p.track.phone": "الموبايل اللي قدّمت بيه",
  "p.track.submit": "اعرف الحالة",
  "p.track.status.pending": "طلبك قيد المراجعة",
  "p.track.status.approved": "اتقبل. هيوصلك رابط التفعيل",
  "p.track.status.rejected": "اتعذّر قبول الطلب",
  "p.track.status.needs_info": "محتاجين منك معلومات تانية",
  "p.track.note": "رسالة من الإدارة",

  /* ---- التفعيل والاستعادة ---- */
  "p.activate.title": "فعّل حسابك",
  "p.activate.sub": "اختار كلمة سر لحسابك. الرابط بيشتغل مرة واحدة.",
  "p.reset.title": "كلمة سر جديدة",
  "p.reset.sub": "اختار كلمة سر جديدة لحسابك.",
  "p.activate.hello": "أهلاً {name}",
  "p.activate.password": "كلمة السر",
  "p.activate.confirm": "اكتبها تاني",
  "p.activate.submit": "فعّل الحساب",
  "p.reset.submit": "احفظ كلمة السر",
  "p.activate.mismatch": "كلمتين السر مش زي بعض.",
  "p.activate.short": "كلمة السر لازم تكون 6 حروف على الأقل.",
  "p.activate.noToken": "الرابط ناقص. افتحه تاني من الرسالة اللي وصلتك.",
  "p.activate.badLink": "الرابط ده مش شغال. اطلب رابط جديد من الإدارة أو من «نسيت كلمة السر».",
  "p.activate.done": "حسابك اتفعّل",
  "p.reset.done": "كلمة السر اتغيّرت",
  "p.activate.doneBody": "ادخل بالموبايل أو الإيميل وكلمة السر الجديدة.",
  "p.codes.title": "أكواد الاستعادة",
  "p.codes.body": "لو نسيت كلمة السر، أي كود من دول يرجّعلك حسابك. كل كود بيشتغل مرة واحدة، ومش هتشوفهم تاني.",
  "p.codes.download": "نزّل الأكواد",
  "p.codes.copy": "انسخ الأكواد",
  "p.codes.saved": "حفظتهم",
  "p.codes.confirm": "اتأكد إنك حفظتهم قبل ما تكمّل.",
  "p.codes.file": "hyper-tech-recovery-codes.txt",

  "p.recover.title": "استعادة الدخول",
  "p.recover.sub": "اختار الطريقة اللي تناسبك.",
  "p.recover.identifier": "الموبايل أو الإيميل",
  "p.recover.method": "الطريقة",
  "p.recover.m.link": "ابعتلي رابط على الإيميل أو تيليجرام",
  "p.recover.m.admin": "معايا كود من الدعم",
  "p.recover.m.recovery": "معايا كود استعادة",
  "p.recover.m.owner": "أنا موظف. اطلب من رئيس الشركة",
  "p.recover.code": "الكود",
  "p.recover.go": "كمّل",
  "p.recover.linkSent": "لو الحساب عليه إيميل أو تيليجرام متأكد، الرابط هيوصلك خلال دقايق.",
  "p.recover.ownerSent": "لو الحساب موجود، رئيس الشركة هيوصله طلبك.",
  "p.recover.support": "كلّم الدعم على واتساب",
  "p.recover.newPassword": "كلمة السر الجديدة",
  "p.recover.codeOk": "الكود صح. اختار كلمة السر الجديدة.",
  "p.recover.save": "احفظ كلمة السر",

  /* ---- الشل ---- */
  "p.nav.home": "الرئيسية",
  "p.nav.products": "المنتجات",
  "p.nav.cart": "السلة",
  "p.nav.orders": "طلباتي",
  "p.nav.companyOrders": "طلبات الشركة",
  "p.nav.account": "حسابي",
  "p.nav.team": "الفريق",
  "p.nav.more": "المزيد",
  "p.nav.main": "التنقل الرئيسي",
  "p.nav.notifications": "الإشعارات",
  "p.nav.logout": "اخرج",
  "p.nav.switchCompany": "غيّر الشركة",
  "p.nav.oldVersion": "ارجع للنسخة القديمة",
  "p.offline": "مفيش نت دلوقتي. اللي بتشوفه ممكن يكون قديم.",
  "p.secure.title": "أمّن حسابك",
  "p.secure.body": "ضيف إيميل أو تيليجرام أو احفظ أكواد استعادة، عشان تقدر ترجع لحسابك لو نسيت كلمة السر.",
  "p.secure.action": "أمّن الحساب",
  "p.mustChange.title": "غيّر كلمة السر المؤقتة",
  "p.mustChange.body": "كلمة السر الحالية مؤقتة. اختار واحدة بتاعتك.",
  "p.mustChange.action": "غيّرها",

  /* ---- الرئيسية ---- */
  "p.home.hello": "أهلاً {name}",
  "p.home.company": "{company}",
  "p.home.latest": "آخر طلباتك",
  "p.home.noOrders": "مفيش طلبات لسه",
  "p.home.noOrdersBody": "ابدأ بتصفح المنتجات وضيف اللي محتاجه للسلة.",
  "p.home.browse": "تصفح المنتجات",
  "p.home.all": "شوف الكل",
  "p.home.reorder": "اطلب تاني",
  "p.home.cartWaiting": "في السلة {n} منتج مستني",
  "p.home.openCart": "افتح السلة",

  /* ---- المنتجات ---- */
  "p.products.title": "المنتجات",
  "p.products.search": "ابحث بالاسم أو الكود",
  "p.products.empty": "مفيش منتجات",
  "p.products.noResults": "مفيش منتج بالاسم ده",
  "p.products.loadFail": "ماقدرناش نحمّل المنتجات.",
  "p.products.min": "أقل كمية للطلب {n} قطعة",
  "p.products.add": "ضيف للسلة",
  "p.products.added": "اتضافت للسلة",
  "p.products.unit": "الوحدة",
  "p.products.qty": "الكمية بالقطعة",
  "p.products.carton": "الكرتونة = {n} {unit}",
  "p.products.cartons": "كراتين",
  "p.products.cartonsHint": "هتتحوّل لقطع: {n}",
  "p.products.byPiece": "بالقطعة",
  "p.products.byCarton": "بالكرتونة",
  "p.products.components": "{n} مكوّن",
  "p.products.featured": "المكونات المميزة",
  "p.products.noImage": "مفيش صورة",
  "p.products.image": "صورة {name}",
  "p.products.gallery": "صور المنتج",
  "p.products.priceAsk": "اسأل عن السعر",
  "p.products.priceSent": "طلب السعر اتبعت. هنرد عليك.",
  "p.products.inCart": "في السلة: {n}",
  "p.products.code": "الكود: {code}",
  "p.products.favorite": "ضيف للمفضلة",
  "p.products.unfavorite": "شيل من المفضلة",
  "p.products.onlyFav": "المفضلة بس",

  /* ---- السلة ---- */
  "p.cart.title": "السلة",
  "p.cart.empty": "السلة فاضية",
  "p.cart.emptyBody": "ضيف منتجات من صفحة المنتجات.",
  "p.cart.total": "{n} منتج، {pieces} قطعة",
  "p.cart.remove": "شيل {name}",
  "p.cart.inc": "زوّد {name}",
  "p.cart.dec": "قلّل {name}",
  "p.cart.qtyOf": "كمية {name}",
  "p.cart.unavailable": "المنتج ده مش متاح دلوقتي. شيله عشان تبعت.",
  "p.cart.priority": "الأولوية",
  "p.cart.pr.low": "مش مستعجل",
  "p.cart.pr.normal": "عادي",
  "p.cart.pr.high": "مهم",
  "p.cart.pr.urgent": "عاجل جدًا",
  "p.cart.notes": "ملاحظات للطلب",
  "p.cart.notesHint": "اختياري. أي حاجة تهمنا نعرفها.",
  "p.cart.review": "راجع وابعت",
  "p.cart.confirmTitle": "تبعت الطلب؟",
  "p.cart.confirmBody": "هيوصل للإدارة مباشرة. {n} منتج، {pieces} قطعة.",
  "p.cart.send": "ابعت الطلب",
  "p.cart.sending": "بنبعت...",
  "p.cart.noPermission": "مالكش صلاحية تبعت طلبات. كلّم رئيس الشركة.",
  "p.cart.limit": "لو محتاج أكتر، اطلب من رئيس الشركة يرفع الحد.",
  "p.cart.success.title": "طلبك وصل",
  "p.cart.success.ref": "رقم المتابعة",
  "p.cart.success.body": "الإدارة هتراجعه وهتوصلك إشعارات بكل خطوة.",
  "p.cart.success.orders": "شوف طلباتي",
  "p.cart.success.more": "اطلب حاجة تانية",
  "p.cart.qtyChanged": "اتحدّثت الكمية",

  /* ---- الطلبات ---- */
  "p.orders.title": "طلباتي",
  "p.orders.companyTitle": "طلبات الشركة",
  "p.orders.scope.mine": "طلباتي أنا",
  "p.orders.scope.all": "كل الشركة",
  "p.orders.scope.label": "عرض",
  "p.orders.empty": "مفيش طلبات لسه",
  "p.orders.emptyBody": "أول ما تبعت طلب هيظهر هنا بخطواته.",
  "p.orders.more": "حمّل أكتر",
  "p.orders.batch": "طلب {ref}",
  "p.orders.items": "{n} منتج",
  "p.orders.by": "بعته {name}",
  "p.orders.byMe": "إنت",
  "p.orders.qty": "{qty} {unit}",
  "p.orders.due": "التسليم المتوقع: {date}",
  "p.orders.reply": "رد الإدارة",
  "p.orders.reason": "السبب: {reason}",
  "p.orders.cancel": "إلغاء الصنف",
  "p.orders.cancelTitle": "تلغي {name}؟",
  "p.orders.cancelBody": "الإلغاء مينفعش يترجع.",
  "p.orders.cancelLate": "الصنف ده بدأ تشغيله. الإلغاء دلوقتي ممكن يكون ليه أثر، والإدارة هتتواصل معاك.",
  "p.orders.cancelReason": "سبب الإلغاء (اختياري)",
  "p.orders.cancelled": "الصنف اتلغى",
  "p.orders.reorder": "اطلب تاني",
  "p.orders.reordered": "ضفنا الأصناف للسلة. راجع الكميات.",
  "p.orders.detail": "تفاصيل الطلب",
  "p.orders.timeline": "خطوات التنفيذ",
  "p.orders.status.pending_review": "مستني مراجعة",
  "p.orders.status.in_progress": "شغّال عليه",
  "p.orders.status.all_completed": "خلص",
  "p.orders.status.needs_attention": "محتاج انتباهك",
  "p.orders.status.all_cancelled": "اتلغى",
  "p.orders.notFound": "الطلب ده مش في القايمة. ممكن يكون في صفحة أقدم.",
  "p.orders.back": "كل الطلبات",

  /* ---- الإشعارات ---- */
  "p.notif.title": "الإشعارات",
  "p.notif.empty": "مفيش إشعارات",
  "p.notif.emptyBody": "هنبلّغك هنا بأي جديد في طلباتك.",
  "p.notif.markAll": "علّم الكل مقروء",
  "p.notif.unread": "{n} جديد",

  /* ---- حسابي ---- */
  "p.account.title": "حسابي",
  "p.account.tab.profile": "بياناتي",
  "p.account.tab.security": "الأمان",
  "p.account.tab.prefs": "تفضيلاتي",
  "p.account.name": "الاسم",
  "p.account.phone": "الموبايل",
  "p.account.email": "الإيميل",
  "p.account.company": "الشركة",
  "p.account.role": "دورك",
  "p.account.owner": "رئيس الشركة",
  "p.account.none": "غير مسجّل",
  "p.account.profileNote": "لتعديل بياناتك كلّم الإدارة.",
  "p.account.logout": "اخرج من الحساب",

  "p.sec.password": "كلمة السر",
  "p.sec.current": "كلمة السر الحالية",
  "p.sec.new": "كلمة السر الجديدة",
  "p.sec.confirm": "اكتب الجديدة تاني",
  "p.sec.change": "غيّر كلمة السر",
  "p.sec.changed": "كلمة السر اتغيّرت",
  "p.sec.sessions": "الأجهزة اللي داخلة",
  "p.sec.thisDevice": "الجهاز ده",
  "p.sec.lastActive": "آخر نشاط {when}",
  "p.sec.revoke": "اخرج منه",
  "p.sec.revoked": "الجهاز اتفصل",
  "p.sec.revokeOthers": "اخرج من كل الأجهزة التانية",
  "p.sec.revokedOthers": "اتفصلت الأجهزة التانية",
  "p.sec.channels": "طرق الاستعادة",
  "p.sec.channelsBody": "الإيميل وتيليجرام بيوصّلولك رابط استعادة وتنبيهات أمان.",
  "p.sec.addEmail": "ضيف إيميل",
  "p.sec.emailSent": "بعتنالك كود على الإيميل.",
  "p.sec.emailFail": "ماقدرناش نبعت الإيميل دلوقتي.",
  "p.sec.emailCode": "كود التأكيد",
  "p.sec.verify": "أكّد",
  "p.sec.emailAdded": "الإيميل اتأكد واتحفظ",
  "p.sec.linkTelegram": "اربط تيليجرام",
  "p.sec.telegramOpen": "افتح تيليجرام واضغط Start",
  "p.sec.telegramNone": "تيليجرام مش متظبط لسه.",
  "p.sec.removeChannel": "شيل",
  "p.sec.channelRemoved": "اتشالت",
  "p.sec.noChannels": "لسه ماضفتش طريقة",
  "p.sec.verified": "متأكد",
  "p.sec.email": "إيميل",
  "p.sec.telegram": "تيليجرام",
  "p.sec.codesLeft": "باقي {n} كود استعادة",
  "p.sec.codesNone": "ماعندكش أكواد استعادة",
  "p.sec.newCodes": "اعمل أكواد جديدة",
  "p.sec.newCodesBody": "الأكواد القديمة هتتبطل. اكتب كلمة السر الحالية.",
  "p.sec.codesMade": "الأكواد الجديدة",

  "p.prefs.theme": "الشكل",
  "p.prefs.mode": "الوضع",
  "p.prefs.accent": "اللون",
  "p.prefs.density": "الكثافة",
  "p.prefs.cozy": "مريحة",
  "p.prefs.compact": "مضغوطة",
  "p.prefs.fontScale": "حجم الخط",

  /* ---- مشترك ---- */
  "p.err.load": "ماقدرناش نحمّل الصفحة.",
  "p.back": "رجوع",
  "p.forbidden.title": "الصفحة دي مش متاحة ليك",
  "p.forbidden.body": "مالكش صلاحية هنا. لو محتاجها كلّم رئيس الشركة.",
  "p.notFound.title": "الصفحة مش موجودة",
  "p.notFound.home": "روح للرئيسية",
  "p.loading": "ثواني...",

  /* ---- الفريق ---- */
  "p.team.title": "الفريق",
  "p.team.tab.members": "الموظفين",
  "p.team.tab.requests": "طلبات الانضمام",
  "p.team.tab.activity": "النشاط",
  "p.team.seats": "{n} من {max} موظف",
  "p.team.add": "ضيف موظف",
  "p.team.empty": "مفيش موظفين لسه",
  "p.team.owner": "رئيس الشركة",
  "p.team.status.active": "شغّال",
  "p.team.status.suspended": "موقوف",
  "p.team.status.invited": "مدعو",
  "p.team.status.pending_approval": "مستني الموافقة",
  "p.team.lastSeen": "آخر ظهور {when}",
  "p.team.neverSeen": "لسه ما دخلش",
  "p.team.suspend": "أوقف",
  "p.team.reactivate": "رجّع",
  "p.team.remove": "شيل",
  "p.team.changeRole": "غيّر الدور",
  "p.team.resetLink": "رابط كلمة سر جديدة",
  "p.team.confirmRemove": "تشيل {name} من الشركة؟",
  "p.team.confirmRemoveBody": "هيتفصل من كل الأجهزة فورًا، وطلباته القديمة هتفضل زي ما هي.",
  "p.team.done": "اتحفظ",
  "p.team.code.title": "كود الشركة",
  "p.team.code.body": "ادّي الكود ده للموظف عشان ينضم من صفحة الانضمام.",
  "p.team.code.copy": "انسخ الكود",
  "p.team.code.copied": "الكود اتنسخ",
  "p.team.code.rotate": "كود جديد",
  "p.team.code.rotateBody": "الكود القديم هيقف يشتغل فورًا.",
  "p.team.code.qr": "QR للكود",
  "p.team.code.uses": "اتستخدم {n} مرة",
  "p.team.code.none": "مفيش كود شغّال دلوقتي.",
  "p.team.join.mode": "الانضمام بالكود",
  "p.team.join.approval": "بموافقتك",
  "p.team.join.auto": "مباشر",
  "p.team.join.disabled": "مقفول",
  "p.team.req.empty": "مفيش طلبات انضمام",
  "p.team.req.approve": "اقبل",
  "p.team.req.reject": "ارفض",
  "p.team.add.title": "ضيف موظف",
  "p.team.add.body": "هنعمله حساب بكلمة سر مؤقتة، وتبعتهاله على واتساب.",
  "p.team.add.name": "الاسم",
  "p.team.add.phone": "الموبايل",
  "p.team.add.email": "الإيميل (اختياري)",
  "p.team.add.role": "الدور",
  "p.team.add.jobTitle": "المسمى الوظيفي (اختياري)",
  "p.team.add.submit": "ضيفه",
  "p.team.add.doneTitle": "الموظف اتضاف",
  "p.team.add.doneBody": "ابعتله بياناته دلوقتي. كلمة السر دي مش هتظهر تاني.",
  "p.team.add.tempPassword": "كلمة السر المؤقتة",
  "p.team.add.whatsapp": "ابعت على واتساب",
  "p.team.add.copyMsg": "انسخ الرسالة",
  "p.team.link.title": "رابط كلمة سر جديدة",
  "p.team.link.body": "الرابط ده بيشتغل مرة واحدة. ابعته للموظف.",
  "p.team.link.sent": "اتبعت كمان على قنواته المفعّلة.",
  "p.team.act.empty": "مفيش نشاط لسه",
  "p.team.act.more": "أقدم من كده",
  "p.team.act.by": "بواسطة {who}",
  "p.team.act.system": "النظام",
  "p.team.act.member.created": "ضاف موظف",
  "p.team.act.member.updated": "عدّل بيانات موظف",
  "p.team.act.member.password_reset": "عمل كلمة سر جديدة لموظف",
  "p.team.act.member.suspended": "أوقف موظف",
  "p.team.act.member.reactivated": "رجّع موظف",
  "p.team.act.member.removed": "شال موظف",
  "p.team.act.join.approved": "قبل طلب انضمام",
  "p.team.act.join.rejected": "رفض طلب انضمام",
  "p.team.act.company.code_rotated": "غيّر كود الشركة",
  "p.team.act.role.created": "عمل دور جديد",
  "p.team.act.role.updated": "عدّل دور",
  "p.team.act.role.deleted": "مسح دور",
  "p.team.act.setting.changed": "غيّر إعداد",
  "p.team.act.other": "إجراء",
} as const;
