/**
 * Generates web/src/design/tokens/generated.css from palette.ts.
 *   npx tsx web/scripts/build-tokens.ts
 * Do not edit generated.css by hand.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  DEFAULTS,
  FAMILIES,
  ROLES,
  chromaFactor,
  lightnessOf,
  stepsOf,
  type Ref,
  type ScaleName,
} from "../src/design/tokens/palette";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, "../src/design/tokens/generated.css");

const fmt = (n: number) => String(Number(n.toFixed(4)));

function primitive(name: ScaleName, step: number): string {
  const fam = FAMILIES[name];
  const L = fmt(lightnessOf(name, step));
  const f = chromaFactor(name, step);
  const c =
    fam.chroma === "var"
      ? f === 1
        ? `var(${fam.chromaVar})`
        : `calc(var(${fam.chromaVar}) * ${fmt(f)})`
      : fmt((fam.chroma as number) * f);
  const h = fam.hue === "var" ? `var(${fam.hueVar})` : String(fam.hue);
  return `oklch(${L} ${c} ${h})`;
}

const varName = (ref: Ref) => {
  const [n, s] = ref.split(".") as [ScaleName, string];
  return `--${n === "neutral" ? "n" : n}-${s}`;
};

function primitives(): string {
  const lines: string[] = [];
  (Object.keys(FAMILIES) as ScaleName[]).forEach((name) => {
    stepsOf(name).forEach((s) => {
      lines.push(`  ${varName(`${name}.${s}` as Ref)}: ${primitive(name, s)};`);
    });
  });
  return lines.join("\n");
}

function roles(mode: "light" | "dark"): string {
  return Object.entries(ROLES)
    .map(([k, v]) => `  --c-${k}: var(${varName(v[mode])});`)
    .join("\n");
}

const darkExtras = `  color-scheme: dark;
  --shadow-1: 0 1px 2px oklch(0 0 0 / 0.5);
  --shadow-2: 0 4px 14px oklch(0 0 0 / 0.5), 0 1px 3px oklch(0 0 0 / 0.4);
  --shadow-3: 0 18px 48px oklch(0 0 0 / 0.6), 0 4px 12px oklch(0 0 0 / 0.4);
  --scrim: oklch(0 0 0 / 0.62);`;

const css = `/* AUTO-GENERATED by web/scripts/build-tokens.ts — لا تعدّل الملف ده بإيدك */

/* ---------- 1) primitives ---------- */
:root {
  --brand-h: ${DEFAULTS.brandHue};
  --brand-c: ${DEFAULTS.brandChroma};
  --n-h: ${DEFAULTS.warm.h};
  --n-c: ${DEFAULTS.warm.c};
${primitives()}
}
:root[data-tone="cool"] {
  --n-h: ${DEFAULTS.cool.h};
  --n-c: ${DEFAULTS.cool.c};
}

/* ---------- 2) semantic roles (light is the base) ---------- */
:root {
  color-scheme: light;
${roles("light")}
  --shadow-1: 0 1px 2px oklch(0.2 0.02 260 / 0.08);
  --shadow-2: 0 4px 14px oklch(0.2 0.02 260 / 0.1), 0 1px 3px oklch(0.2 0.02 260 / 0.06);
  --shadow-3: 0 18px 48px oklch(0.2 0.02 260 / 0.18), 0 4px 12px oklch(0.2 0.02 260 / 0.08);
  --scrim: oklch(0.2 0.02 260 / 0.45);
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${roles("dark")}
${darkExtras}
  }
}
:root[data-theme="dark"] {
${roles("dark")}
${darkExtras}
}

/* ---------- 3) shape, type, space, motion ---------- */
:root {
  --radius-scale: 1;
  --r-xs: calc(4px * var(--radius-scale));
  --r-sm: calc(8px * var(--radius-scale));
  --r-md: calc(12px * var(--radius-scale));
  --r-lg: calc(18px * var(--radius-scale));
  --r-pill: 999px;

  --font-ui: "Tajawal", system-ui, -apple-system, "Segoe UI", Tahoma, sans-serif;
  --font-mono: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  --font-scale: 1;
  --fs-xs: calc(0.75rem * var(--font-scale));
  --fs-sm: calc(0.875rem * var(--font-scale));
  --fs-md: calc(1rem * var(--font-scale));
  --fs-lg: calc(1.175rem * var(--font-scale));
  --fs-xl: calc(1.4rem * var(--font-scale));
  --fs-2xl: calc(1.8rem * var(--font-scale));
  --fs-3xl: calc(2.4rem * var(--font-scale));
  --lh-tight: 1.3;
  --lh-body: 1.7;

  --sp-1: 4px;
  --sp-2: 8px;
  --sp-3: 12px;
  --sp-4: 16px;
  --sp-5: 24px;
  --sp-6: 32px;
  --sp-7: 48px;
  --sp-8: 72px;

  /* density: cozy (default) / compact */
  --control-h: 44px;
  --control-px: 14px;
  --row-py: 14px;
  --gap-field: 18px;

  --ease: cubic-bezier(0.2, 0.7, 0.2, 1);
  --dur-1: 120ms;
  --dur-2: 200ms;
  --dur-3: 320ms;

  --z-sticky: 20;
  --z-drawer: 60;
  --z-dialog: 70;
  --z-popover: 80;
  --z-toast: 90;

  --ring-w: 3px;
  --ring-offset: 2px;
}
:root[data-density="compact"] {
  --control-h: 36px;
  --control-px: 10px;
  --row-py: 8px;
  --gap-field: 12px;
}
@media (prefers-reduced-motion: reduce) {
  :root {
    --dur-1: 0ms;
    --dur-2: 0ms;
    --dur-3: 0ms;
  }
}
`;

writeFileSync(OUT, css);
console.log(`tokens: ${OUT.replace(process.cwd() + "/", "")} (${css.length} bytes)`);
